<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.omnaest.utils</groupId>
		<artifactId>CommonsParent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>org.omnaest.utils</groupId>
	<artifactId>CommonsNeuralNetwork</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>CommonsNeuralNetwork</name>
	<description>Small dependency free feedforward neural network with backpropagation training.</description>
	<url>https://github.com/omnaest/CommonsNeuralNetwork</url>
	<scm>
		<connection>scm:git:git://github.com/omnaest/CommonsNeuralNetwork.git</connection>
		<developerConnection>scm:git:ssh://github.com/omnaest/CommonsNeuralNetwork.git</developerConnection>
		<url>https://github.com/omnaest/CommonsNeuralNetwork</url>
	</scm>

	<dependencies>
		<dependency>
			<groupId>org.omnaest.utils</groupId>
			<artifactId>CommonsTest</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
